// Additional search destinations, merged into the existing country catalog at build time.
export const LOCATION_ADDITIONS = {
  "European Union": {},
  Romania: {
    Alba: ["Alba Iulia", "Sebeș"],
    Arad: ["Arad"],
    Argeș: ["Pitești", "Curtea de Argeș"],
    Bacău: ["Bacău", "Onești"],
    Bihor: ["Oradea"],
    "Bistrița-Năsăud": ["Bistrița"],
    Botoșani: ["Botoșani"],
    Brașov: ["Brașov", "Făgăraș"],
    Brăila: ["Brăila"],
    Bucharest: ["Bucharest"],
    Buzău: ["Buzău"],
    "Caraș-Severin": ["Reșița", "Caransebeș"],
    Călărași: ["Călărași"],
    Cluj: ["Cluj-Napoca", "Turda", "Dej"],
    Constanța: ["Constanța", "Mangalia"],
    Covasna: ["Sfântu Gheorghe"],
    Dâmbovița: ["Târgoviște"],
    Dolj: ["Craiova"],
    Galați: ["Galați"],
    Giurgiu: ["Giurgiu"],
    Gorj: ["Târgu Jiu"],
    Harghita: ["Miercurea Ciuc", "Odorheiu Secuiesc"],
    Hunedoara: ["Deva", "Hunedoara", "Petroșani"],
    Ialomița: ["Slobozia"],
    Iași: ["Iași", "Pașcani"],
    Ilfov: ["Voluntari", "Otopeni", "Buftea"],
    Maramureș: ["Baia Mare", "Sighetu Marmației"],
    Mehedinți: ["Drobeta-Turnu Severin"],
    Mureș: ["Târgu Mureș", "Sighișoara"],
    Neamț: ["Piatra Neamț", "Roman"],
    Olt: ["Slatina", "Caracal"],
    Prahova: ["Ploiești", "Câmpina", "Sinaia"],
    "Satu Mare": ["Satu Mare"],
    Sălaj: ["Zalău"],
    Sibiu: ["Sibiu", "Mediaș"],
    Suceava: ["Suceava", "Fălticeni"],
    Teleorman: ["Alexandria"],
    Timiș: ["Timișoara", "Lugoj"],
    Tulcea: ["Tulcea"],
    Vaslui: ["Vaslui", "Bârlad"],
    Vâlcea: ["Râmnicu Vâlcea"],
    Vrancea: ["Focșani"],
  },
  Remote: {},
};
